# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import main.media_path


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.media_path.blog_image_upload_path, verbose_name='Изображение'),
        ),
    ]
